ATTRIBUTE_GROUP = 'fusion_scripts'
ATTRIBUTE_NAME_KEY = 'name'

BODY_INNER_SHELL = '内殻'
BODY_OUTER_SHELL_BASE_STRUCTURE = '外殻基準構造'
BODY_OUTER_SHELL = BODY_OUTER_SHELL_BASE_STRUCTURE
BODY_GRIP = 'グリップ'

GRIP_PARAM_WIDTH_MM = 'width_mm'
GRIP_PARAM_HEIGHT_MM = 'height_mm'
GRIP_PARAM_DEPTH_MM = 'depth_mm'
GRIP_PARAM_OFFSET_X_MM = 'offset_x_mm'
GRIP_PARAM_OFFSET_Y_MM = 'offset_y_mm'
GRIP_PARAM_OFFSET_Z_MM = 'offset_z_mm'

DEFAULT_GRIP_PARAMS = {
    GRIP_PARAM_WIDTH_MM: 0.0,
    GRIP_PARAM_HEIGHT_MM: 0.0,
    GRIP_PARAM_DEPTH_MM: 0.0,
    GRIP_PARAM_OFFSET_X_MM: 0.0,
    GRIP_PARAM_OFFSET_Y_MM: 0.0,
    GRIP_PARAM_OFFSET_Z_MM: 0.0,
}

DEFAULT_OUTER_SHELL_PARAMS = {
    'clearance_mm': 0.2,
    'wall_thickness_mm': 1.0,
}
